//USER
export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_USER = "LOGIN_USER";

//STOCK
export const PURCHASE_STOCK = "PURCHASE_STOCK";
export const FAILED_LOGIN = "FAILED_LOGIN";
export const FAILED_PURCHASE = "FAILED_PURCHASE";

//League
export const CREATE_LEAGUE = "CREATE_LEAGUE"
export const FAILED_LEAGUE = "FAILED_LEAGUE"
export const JOIN_LEAGUE = "JOIN_LEAGUE"
export const FAILED_JOIN_LEAGUE = "FAILED_JOIN_LEAGUE"
export const RESET_ERROR_JOIN_LEAGUE = "RESET_ERROR_JOIN_LEAGUE"
